export const state = {
  CHUNK_THRESHOLD:    5  * 1024 * 1024,
  CHUNK_SIZE:         10 * 1024 * 1024,
  MAX_FILE_SIZE:      5  * 1024 * 1024 * 1024,
  UPLOAD_CONCURRENCY: 4,
  FILES_CACHE_TTL:    30_000,
  uploadPending:    [],
  uploadActive:     false,
  uploadPaused:     false,
  uploadAbortFn:    null,
  shareFile:        null,
  allRepos:         [],
  activeRepoIdx:    0,
  repoFiles:        [],
  repoStorage:      [],
  currentFileRepoIdx: 0,
  editFile:         null,
  editSha:          null,
  filesCachedAt:    0,
  sliceCache:       new WeakMap(),
};
